### PR TITLE
FIX: power measure for Washer and Dryer

### PR DESCRIPTION
**Pull request by martijnpoppen**
Not sure if this fixes it, but looks like this works as a quickfix

### CODE REVIEW

**Comment by AdyRock** [comment]
Thanks for your support, I appreciate the help.
I have merged your changes but when I am testing it, I think the adjustment needs to take into account the divider.
My current Energy is 739.4 kWh and the power is showing 0.74 W, so value is read in as 739400 and the capability is read back as 0.7393992606007393. Therefore the adjusted value is 739400 - 0.7393992606007393.
Are you seeing something different?

**Comment by AdyRock** [comment]
Second thoughts, that doesn't work either as then my power just alternates between 0.74 and 0.
I guess your intention is to set the power to the difference between each reading of the Energy. So we need  P = E - E[-1] rather than P= E - P.

**Comment by AdyRock** [comment]
I have update the master with a possible fix so could you check that it still works for you.
I might need to add a block to ensure Energy is updated before Power but for me the order of updates is currently OK.

**Comment by martijnpoppen** [comment]
> Are you seeing something different?

No you're right, saw the same today.

I'll check the latest master branch! :)

**Comment by martijnpoppen** [comment]
Did test it. But for me it stayed on 0W :/

**Comment by AdyRock** [comment]
I will investigate further. It could be the order in which the data is collected or maybe the Energy changes slower than the update rate.

**Pull request merged**
